# Generated by Django 4.1.5 on 2023-01-15 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('quantity', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('house', models.CharField(max_length=10)),
                ('pay_method', models.CharField(choices=[('cash', 'cash'), ('visa', 'visa'), ('paypal', 'paypal')], max_length=10)),
                ('good', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
