# Generated by Django 4.1.5 on 2023-01-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_comment_date_alter_goods_image_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='sale',
            field=models.BooleanField(default=False),
        ),
    ]
