# Generated by Django 4.1.5 on 2023-01-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_goods_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('cash', 'cash'), ('visa', 'visa')], max_length=10),
        ),
    ]
